### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront 用戶端安全性
  description: Microsoft Forefront Client Security 遵循固定生命週期原則。
  ms.date: 08/28/2020
  ms.openlocfilehash: 335ae81ffa4b7cb64352b19e7330765a4cac6c68
  ms.sourcegitcommit: 570c824dbe19150d37398333df7d2c416a51eac9
  ms.translationtype: MT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 08/28/2020
  ms.locfileid: "924246"
name: Microsoft Forefront 用戶端安全性
summary: >+
  Microsoft Forefront Client Security 遵循 [固定](/lifecycle/policies/fixed) 生命週期原則。


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>連結 \n* [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront 用戶端安全性從2015年7月14日起已中止。 在產品版本的支援結束後，反惡意程式碼和反間諜軟體定義更新將不再提供。 請將 System Center Endpoint Protection 評估為取代。"
