### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center 2012 Configuration Manager
  description: Microsoft System Center 2012 Configuration Manager 遵循固定生命週期原則。
  ms.date: 07/28/2020
  ms.openlocfilehash: dce8796f280b29e070bbf1d5bab55452f6e706e7
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "849835"
name: Microsoft System Center 2012 Configuration Manager
summary: >+
  Microsoft System Center 2012 Configuration Manager 遵循[固定](/lifecycle/policies/fixed)生命週期原則。


products:
- msc
policyType: fixed
supportDates:
  start: 05/30/2012
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
- version: Service Pack 2
  startDate: 05/12/2015
  endDate: 07/12/2022
- version: Service Pack 1
  startDate: 12/15/2012
  endDate: 07/12/2016
- version: Original Release
  startDate: 05/30/2012
  endDate: 01/14/2014
content: "\n## <a name=\"links\"></a>Links \n* [Service pack 原則](/lifecycle/policies/fixed#service-packs)\n* [System Center 檔](/system-center/#pivot=components&panel=components-all)\n* [System Center 資源](https://www.microsoft.com/system-center/resources)"
