### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 遵循固定生命週期原則。
  ms.date: 07/28/2020
  ms.openlocfilehash: 1066e1999c057459643c64aba46bb88e34bb4842
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4137412"
name: Microsoft System Center Configuration Manager 2007 R3
summary: >
  Microsoft System Center Configuration Manager 2007 R3 遵循[固定](/lifecycle/policies/fixed)生命週期原則。



  > [!IMPORTANT]

  > 此產品的支援已終止。 請參閱下面的移轉指引。
products:
- msc
policyType: fixed
supportDates:
  start: 2010-12-19T00:00:00.000-08:00
  end: 2014-07-08T22:59:59.999-08:00
  extendedEnd: 2019-07-09T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2010-12-19T00:00:00.000-08:00
  endDate: 2019-07-09T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>連結 \n* [移轉指引](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [其他移轉指導方針](/mem/configmgr/core/migration/planning-for-migration)"
