### YamlMime:Lifecycle
metadata:
  title: 適用于 Windows 桌面的 Microsoft Application Virtualization Hosting 5.0
  description: Microsoft Application Virtualization Hosting 5.0 for Windows Desktops 遵循固定生命週期原則。
  ms.date: 09/01/2020
  keywords: for Windows Desktops
name: 適用于 Windows 桌面的 Microsoft Application Virtualization Hosting 5.0
summary: |+
  Microsoft Application Virtualization Hosting 5.0 for Windows Desktops 遵循[固定](/lifecycle/policies/fixed)生命週期原則。

  本文適用於下列版本：適用於 Windows Desktops

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2012
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
  - version: Service Pack 3
    startDate: 12/08/2014
    endDate: 04/14/2026
  - version: Service Pack 2
    startDate: 11/08/2013
    endDate: 01/12/2016
  - version: Service Pack 1
    startDate: 04/10/2013
    endDate: 01/13/2015
  - version: Original Release
    startDate: 11/01/2012
    endDate: 07/08/2014
content: |

  ## <a name="links"></a>連結 
  * [產品資訊](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)
  * [Service Pack 原則](/lifecycle/policies/fixed#service-packs)


  ## <a name="editions"></a>版本 
  * 適用於 Windows Desktops