### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center 2012 Configuration Manager
  description: Microsoft System Center 2012 Configuration Manager 遵循固定生命週期原則。
  ms.date: 03/12/2021
  keywords: 
  ms.openlocfilehash: f710122044be40b9cbaf957f7c6ca06ea520fbd0
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4112585"
name: Microsoft System Center 2012 Configuration Manager
summary: >+
  Microsoft System Center 2012 Configuration Manager 遵循[固定](/lifecycle/policies/fixed)生命週期原則。


products:
- msc
policyType: fixed
supportDates:
  start: 2012-05-30T00:00:00.000-08:00
  end: 2017-07-11T22:59:59.999-08:00
  extendedEnd: 2022-07-12T22:59:59.999-08:00
releases:
- version: Service Pack 2
  startDate: 2015-05-12T00:00:00.000-08:00
  endDate: 2022-07-12T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2012-12-15T00:00:00.000-08:00
  endDate: 2016-07-12T22:59:59.999-08:00
- version: Original Release
  startDate: 2012-05-30T00:00:00.000-08:00
  endDate: 2014-01-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>連結 \n* [Service Pack 原則](/lifecycle/policies/fixed#service-packs)\n* [System Center 文件](/system-center/#pivot=components&panel=components-all)\n* [System Center 資源](https://www.microsoft.com/system-center/resources)\n* [移轉指引](https://techcommunity.microsoft.com/t5/configuration-manager-blog/system-center-2012-configuration-manager-is-approaching-end-of/ba-p/1650899)"
