### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager (LTSB - 1606 版)
  description: Microsoft System Center Configuration Manager (LTSB - 1606 版) 遵循固定生命週期原則。
  ms.date: 08/20/2020
  ms.openlocfilehash: c918fa35a50ffac8ee9d31cb0b704aac444cefe1
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4106184"
name: Microsoft System Center Configuration Manager (LTSB - 1606 版)
summary: >+
  Microsoft System Center Configuration Manager (LTSB - 1606 版) 遵循[固定](/lifecycle/policies/fixed)生命週期原則。


products:
- m365
policyType: fixed
supportDates:
  start: 2016-10-12T00:00:00.000-08:00
  end: 2021-10-12T22:59:59.999-08:00
  extendedEnd: 2027-01-12T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2016-10-12T00:00:00.000-08:00
  endDate: 2027-01-12T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>連結 \n* [服務與支援資訊](/sccm/core/understand/learn-more-editions)"
