### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R2
  description: Microsoft System Center Configuration Manager 2007 R2 遵循固定生命週期原則。
  ms.date: 07/28/2020
  ms.openlocfilehash: 0da71b9a2886e1a7012339ebef9a5fbe64f8811e
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "807398"
name: Microsoft System Center Configuration Manager 2007 R2
summary: >
  Microsoft System Center Configuration Manager 2007 R2 遵循[固定](/lifecycle/policies/fixed)生命週期原則。



  > [!IMPORTANT]

  > 已結束對此產品的支援。 請參閱下列遷移指南。
products:
- msc
policyType: fixed
supportDates:
  start: 11/29/2008
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 11/29/2008
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Links \n* [遷移指引](/mem/configmgr/core/migration/planning-for-migration)\n* [其他遷移指引](/mem/configmgr/core/migration/migrate-data-between-hierarchies)"
