### YamlMime:Lifecycle
metadata:
  title: 適用于 Windows 桌面的 Microsoft Application Virtualization （主控4.6）
  description: Microsoft Application Virtualization 主控 4.6 for Windows 桌面遵循固定生命週期原則。
  ms.date: 07/28/2020
  ms.openlocfilehash: 21ed557cd6333e43a274796a3b25791c0d7f96cd
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "807516"
name: 適用于 Windows 桌面的 Microsoft Application Virtualization （主控4.6）
summary: >+
  Microsoft Application Virtualization 主控 4.6 for Windows 桌面遵循[固定](/lifecycle/policies/fixed)生命週期原則。


  這適用于下列版本：適用于 Windows 桌面

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Links \n* [產品及遷移資訊](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Service pack 原則](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> 從 App-V 4.6 用戶端使用 App-V 4.5 伺服器，App-V 4.5 伺服器會在與支援的 App-V 4.6 用戶端搭配使用時，依照 App-V 4.6 的週期日期繼續受到支援。\n\n## <a name=\"editions\"></a>版本 \n* 適用于 Windows 桌面"
