### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront 用戶端安全性
  description: Microsoft Forefront Client Security 遵循固定生命週期原則。
  ms.date: 08/21/2020
  ms.openlocfilehash: 802c6836324ac39b0b8ffc99c1f7f6734906445b
  ms.sourcegitcommit: 2f3e18a9447115504ef274bd044dbcdb08231f5b
  ms.translationtype: MT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 08/25/2020
  ms.locfileid: "908650"
name: Microsoft Forefront 用戶端安全性
summary: >+
  Microsoft Forefront Client Security 遵循 [固定](/lifecycle/policies/fixed) 生命週期原則。


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>連結 \n* [System Center Endpoint Protection](http://www.microsoft.com/server-cloud/products/system-center-2012-r2-configuration-manager/default.aspx)\n\n> [!NOTE]\n> Forefront 用戶端安全性已經停產。 支援可于2015年7月14日結束。 在產品版本的支援結束後，反惡意程式碼和反間諜軟體定義更新將不再提供。 請將 System Center Endpoint Protection 評估為取代。"
