### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 遵循固定生命週期原則。
  ms.date: 07/28/2020
  ms.openlocfilehash: cffcc1c2bb51fc5023fe6ad29d62132141ffedb2
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "850049"
name: Microsoft System Center Configuration Manager 2007 R3
summary: >
  Microsoft System Center Configuration Manager 2007 R3 遵循[固定](/lifecycle/policies/fixed)生命週期原則。



  > [!IMPORTANT]

  > 已結束對此產品的支援。 請參閱下列遷移指南。
products:
- msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 12/19/2010
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Links \n* [遷移指引](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [其他遷移指引](/mem/configmgr/core/migration/planning-for-migration)"
