### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security 遵循固定生命週期原則。
  ms.date: 08/28/2020
  ms.openlocfilehash: d85aea21441458397839241e74939536051397d4
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4113399"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security 遵循[固定](/lifecycle/policies/fixed)生命週期原則。


products:
- msc
policyType: fixed
supportDates:
  start: 2007-08-02T00:00:00.000-08:00
  extendedEnd: 2015-07-14T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2007-08-02T00:00:00.000-08:00
  endDate: 2015-07-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>連結 \n* [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront Client Security 已於 2015 年 7 月 14 日起停止支援。 在產品版本終止支援之後，即不再提供反惡意程式碼和反間諜功能定義更新。 請評估改以 System Center Endpoint Protection 取代。"
